### ISSUE TITLE
Default exception handler: Error al escribir a la base de datos Debug: Table 'moodledred.mdl_registry' doesn't exist

### ISSUE THREAD

**Issue by kfern** [moodlehq/moodle-tool_inspire#1]
Moodle 3.0.3+ (Build: 20160415). mdl_registry table doesn't exist in database

Last lines in screen:

++ Getting rid of all ips ++
* line 435 of /local/anonymise/locallib.php: call to debugging()
* line 126 of /local/anonymise/cli/anonymise.php: call to anonymise_others()
Default exception handler: Error al escribir a la base de datos Debug: Table 'moodledred.mdl_registry' doesn't exist
UPDATE mdl_registry SET ipaddress = ?
[array (
  0 => '0.0.0.0',
)]
Error code: dmlwriteexception
* line 446 of /lib/dml/moodle_database.php: dml_write_exception thrown
* line 974 of /lib/dml/mysqli_native_moodle_database.php: call to moodle_database->query_end()
* line 444 of /local/anonymise/locallib.php: call to mysqli_native_moodle_database->execute()
* line 126 of /local/anonymise/cli/anonymise.php: call to anonymise_others()

!!! Error al escribir a la base de datos !!!
!! Table 'moodledred.mdl_registry' doesn't exist
UPDATE mdl_registry SET ipaddress = ?
[array (
  0 =&gt; '0.0.0.0',
)]
Error code: dmlwriteexception !!
!! Stack trace: * line 446 of /lib/dml/moodle_database.php: dml_write_exception thrown
* line 974 of /lib/dml/mysqli_native_moodle_database.php: call to moodle_database-&gt;query_end()
* line 444 of /local/anonymise/locallib.php: call to mysqli_native_moodle_database-&gt;execute()
* line 126 of /local/anonymise/cli/anonymise.php: call to anonymise_others()
 !!

**Comment by dmonllao** [comment]
Hi @kfern, this is actually a bug in https://github.com/moodlehq/moodle-local_anonymise, thanks for reporting it.

**Comment by dmonllao** [comment]
I can't create issues in https://github.com/moodlehq/moodle-local_anonymise at the moment I will reopen this until I can move it there / fix it.

**Comment by dmonllao** [comment]
Closing now :) https://github.com/moodlehq/moodle-local_anonymise/issues/1
