### ISSUE TITLE
Plugin install ok but doesn't appear in admin interface

### ISSUE THREAD

**Issue by sebdsti** [moodlehq/moodle-tool_inspire#4]
Hi team,

I've just installed Inspire 2017050902 / v3.3-r3 on my Moodle 3.3+ (Build: 20170525), no core modifications (or any at all really).

The plugin installs fine but nothing appear in the Dashboard / Site administration / Plugins / Admin tools / Inspire or the Reports area.
However, I see Inspire installed in the "Manage Admin Tools" area via /admin/tools.php

Also, if I try /admin/tool/inspire/index.php I get a "section error" and the debug gives:
Stack trace:
line 496 of /lib/setuplib.php: moodle_exception thrown
line 7900 of /lib/adminlib.php: call to print_error()
line 28 of /admin/tool/inspire/index.php: call to admin_externalpage_setup()

Can you guide me?
Thanks
Sebastien

**Comment by dmonllao** [comment]
Hi @sebdsti, sorry for the late reply but I missed this issue. I've seen that error accessing inspire management pages using a user without the required permissions; you shouldn't see any error logged in as an admin.

**Comment by dmonllao** [comment]
I am closing the issue. Feel free to reopen if I am missing something.
